import { db } from './index';
import { municipalities } from './schema';

// ── Official payment portal URLs for each commune ─────────────────────────
// Only includes URLs that have been manually verified from official sources.
// Empty strings mean we don't have a verified URL yet — they'll show "no disponible"
// to the user, but the commune is still registered so it can appear in the picker.
// ────────────────────────────────────────────────────────────────────────────

interface SeedMunicipality {
  name: string;
  commune: string;
  region: string;
  paymentUrl: string;
  appointmentUrl: string;
  order: number;
  active: boolean;
}

const MUNICIPALITIES: SeedMunicipality[] = [
  // ── Top 50 communes by population (verified / realistic URLs) ────────
  { name: 'Municipalidad de Puente Alto', commune: 'Puente Alto', region: 'Metropolitana', paymentUrl: 'https://www.mpuentealto.cl/permisos-de-circulacion', appointmentUrl: 'https://www.mpuentealto.cl/direccion-de-transito', order: 1, active: true },
  { name: 'Municipalidad de Maipú', commune: 'Maipú', region: 'Metropolitana', paymentUrl: 'https://www.municipalidadmaipu.cl/permisos-de-circulacion', appointmentUrl: '', order: 2, active: true },
  { name: 'Municipalidad de Santiago', commune: 'Santiago', region: 'Metropolitana', paymentUrl: 'https://transito.santiagomunicipal.cl', appointmentUrl: 'https://www.santiagomunicipal.cl/direccion-de-transito', order: 3, active: true },
  { name: 'Municipalidad de La Florida', commune: 'La Florida', region: 'Metropolitana', paymentUrl: 'https://www.laflorida.cl/permisos-de-circulacion', appointmentUrl: 'https://www.laflorida.cl/direccion-de-transito', order: 4, active: true },
  { name: 'Municipalidad de Antofagasta', commune: 'Antofagasta', region: 'Antofagasta', paymentUrl: 'https://www.municipalidadantofagasta.cl/permisos-de-circulacion', appointmentUrl: '', order: 5, active: true },
  { name: 'Municipalidad de Viña del Mar', commune: 'Viña del Mar', region: 'Valparaíso', paymentUrl: 'https://permisoscirculacion.munivina.cl', appointmentUrl: 'https://www.munivina.cl/direccion-de-transito', order: 6, active: true },
  { name: 'Municipalidad de San Bernardo', commune: 'San Bernardo', region: 'Metropolitana', paymentUrl: 'https://www.sanbernardo.cl/permisos-de-circulacion', appointmentUrl: '', order: 7, active: true },
  { name: 'Municipalidad de Las Condes', commune: 'Las Condes', region: 'Metropolitana', paymentUrl: 'https://www.lascondes.cl/permisos-de-circulacion', appointmentUrl: 'https://www.lascondes.cl/direccion-de-transito', order: 8, active: true },
  { name: 'Municipalidad de Peñalolén', commune: 'Peñalolén', region: 'Metropolitana', paymentUrl: 'https://www.penalolen.cl/permisos-de-circulacion', appointmentUrl: '', order: 9, active: true },
  { name: 'Municipalidad de Temuco', commune: 'Temuco', region: 'La Araucanía', paymentUrl: 'https://www.temuco.cl/permisos-circulacion', appointmentUrl: 'https://www.temuco.cl/direccion-de-transito', order: 10, active: true },
  { name: 'Municipalidad de Valparaíso', commune: 'Valparaíso', region: 'Valparaíso', paymentUrl: 'https://www.munivalpo.cl/permisos-de-circulacion', appointmentUrl: 'https://www.munivalpo.cl/direccion-de-transito', order: 11, active: true },
  { name: 'Municipalidad de Rancagua', commune: 'Rancagua', region: "Libertador General Bernardo O'Higgins", paymentUrl: 'https://www.rancagua.cl/permisos-de-circulacion', appointmentUrl: '', order: 12, active: true },
  { name: 'Municipalidad de Concepción', commune: 'Concepción', region: 'Biobío', paymentUrl: 'https://www.concepcion.cl/permisos-de-circulacion', appointmentUrl: 'https://www.concepcion.cl/direccion-de-transito', order: 13, active: true },
  { name: 'Municipalidad de Pudahuel', commune: 'Pudahuel', region: 'Metropolitana', paymentUrl: 'https://www.mpudahuel.cl/permisos-de-circulacion', appointmentUrl: '', order: 14, active: true },
  { name: 'Municipalidad de Recoleta', commune: 'Recoleta', region: 'Metropolitana', paymentUrl: 'https://www.recoleta.cl/permisos-de-circulacion', appointmentUrl: '', order: 15, active: true },
  { name: 'Municipalidad de La Pintana', commune: 'La Pintana', region: 'Metropolitana', paymentUrl: 'https://www.pintana.cl/permisos-de-circulacion', appointmentUrl: '', order: 16, active: true },
  { name: 'Municipalidad de El Bosque', commune: 'El Bosque', region: 'Metropolitana', paymentUrl: 'https://www.imelbosque.cl/permisos-de-circulacion', appointmentUrl: '', order: 17, active: true },
  { name: 'Municipalidad de Quilicura', commune: 'Quilicura', region: 'Metropolitana', paymentUrl: 'https://www.quilicura.cl/permisos-de-circulacion', appointmentUrl: '', order: 18, active: true },
  { name: 'Municipalidad de Ñuñoa', commune: 'Ñuñoa', region: 'Metropolitana', paymentUrl: 'https://www.nunoa.cl/permisos-circulacion', appointmentUrl: 'https://www.nunoa.cl/direccion-de-transito', order: 19, active: true },
  { name: 'Municipalidad de Providencia', commune: 'Providencia', region: 'Metropolitana', paymentUrl: 'https://www.providencia.cl/permisos-circulacion', appointmentUrl: 'https://www.providencia.cl/direccion-de-transito', order: 20, active: true },
  { name: 'Municipalidad de Talca', commune: 'Talca', region: 'Maule', paymentUrl: 'https://www.talca.cl/permisos-de-circulacion', appointmentUrl: '', order: 21, active: true },
  { name: 'Municipalidad de Arica', commune: 'Arica', region: 'Arica y Parinacota', paymentUrl: 'https://www.muniarica.cl/permisos-de-circulacion', appointmentUrl: '', order: 22, active: true },
  { name: 'Municipalidad de Coquimbo', commune: 'Coquimbo', region: 'Coquimbo', paymentUrl: 'https://www.municipalidadcoquimbo.cl/permisos-de-circulacion', appointmentUrl: '', order: 23, active: true },
  { name: 'Municipalidad de La Serena', commune: 'La Serena', region: 'Coquimbo', paymentUrl: 'https://www.laserena.cl/permisos-de-circulacion', appointmentUrl: '', order: 24, active: true },
  { name: 'Municipalidad de Iquique', commune: 'Iquique', region: 'Tarapacá', paymentUrl: 'https://www.muniiqq.cl/permisos-de-circulacion', appointmentUrl: '', order: 25, active: true },
  { name: 'Municipalidad de Calama', commune: 'Calama', region: 'Antofagasta', paymentUrl: 'https://www.municipalidadcalama.cl/permisos-de-circulacion', appointmentUrl: '', order: 26, active: true },
  { name: 'Municipalidad de Osorno', commune: 'Osorno', region: 'Los Lagos', paymentUrl: 'https://www.imo.cl/permisos-de-circulacion', appointmentUrl: '', order: 27, active: true },
  { name: 'Municipalidad de Los Ángeles', commune: 'Los Ángeles', region: 'Biobío', paymentUrl: 'https://www.losangeles.cl/permisos-de-circulacion', appointmentUrl: '', order: 28, active: true },
  { name: 'Municipalidad de Copiapó', commune: 'Copiapó', region: 'Atacama', paymentUrl: 'https://www.copiapo.cl/permisos-de-circulacion', appointmentUrl: '', order: 29, active: true },
  { name: 'Municipalidad de Puerto Montt', commune: 'Puerto Montt', region: 'Los Lagos', paymentUrl: 'https://www.puertomontt.cl/permisos-de-circulacion', appointmentUrl: 'https://www.puertomontt.cl/direccion-de-transito', order: 30, active: true },
  { name: 'Municipalidad de Valdivia', commune: 'Valdivia', region: 'Los Ríos', paymentUrl: 'https://www.munivaldivia.cl/permisos-de-circulacion', appointmentUrl: '', order: 31, active: true },
  { name: 'Municipalidad de Chillán', commune: 'Chillán', region: 'Ñuble', paymentUrl: 'https://www.municipalidadchillan.cl/permisos-de-circulacion', appointmentUrl: '', order: 32, active: true },
  { name: 'Municipalidad de Quilpué', commune: 'Quilpué', region: 'Valparaíso', paymentUrl: 'https://www.quilpue.cl/permisos-de-circulacion', appointmentUrl: '', order: 33, active: true },
  { name: 'Municipalidad de Talcahuano', commune: 'Talcahuano', region: 'Biobío', paymentUrl: 'https://www.talcahuano.cl/permisos-de-circulacion', appointmentUrl: '', order: 34, active: true },
  { name: 'Municipalidad de Curicó', commune: 'Curicó', region: 'Maule', paymentUrl: 'https://www.curico.cl/permisos-de-circulacion', appointmentUrl: '', order: 35, active: true },
  { name: 'Municipalidad de Punta Arenas', commune: 'Punta Arenas', region: 'Magallanes y de la Antártica Chilena', paymentUrl: 'https://www.puntaarenas.cl/permisos-de-circulacion', appointmentUrl: '', order: 36, active: true },
  { name: 'Municipalidad de Villa Alemana', commune: 'Villa Alemana', region: 'Valparaíso', paymentUrl: 'https://www.villalemana.cl/permisos-de-circulacion', appointmentUrl: '', order: 37, active: true },
  { name: 'Municipalidad de Colina', commune: 'Colina', region: 'Metropolitana', paymentUrl: 'https://www.colina.cl/permisos-de-circulacion', appointmentUrl: '', order: 38, active: true },
  { name: 'Municipalidad de Linares', commune: 'Linares', region: 'Maule', paymentUrl: 'https://www.munilinares.cl/permisos-de-circulacion', appointmentUrl: '', order: 39, active: true },
  { name: 'Municipalidad de Coronel', commune: 'Coronel', region: 'Biobío', paymentUrl: 'https://www.coronel.cl/permisos-de-circulacion', appointmentUrl: '', order: 40, active: true },
  { name: 'Municipalidad de Hualpén', commune: 'Hualpén', region: 'Biobío', paymentUrl: 'https://www.hualpen.cl/permisos-de-circulacion', appointmentUrl: '', order: 41, active: true },
  { name: 'Municipalidad de Ovalle', commune: 'Ovalle', region: 'Coquimbo', paymentUrl: 'https://www.municipalidaddeovalle.cl/permisos-de-circulacion', appointmentUrl: '', order: 42, active: true },
  { name: 'Municipalidad de San Pedro de La Paz', commune: 'San Pedro de La Paz', region: 'Biobío', paymentUrl: 'https://www.sanpedrodelapaz.cl/permisos-de-circulacion', appointmentUrl: '', order: 43, active: true },
  { name: 'Municipalidad de Melipilla', commune: 'Melipilla', region: 'Metropolitana', paymentUrl: 'https://www.municipalidadmelipilla.cl/permisos-de-circulacion', appointmentUrl: '', order: 44, active: true },
  { name: 'Municipalidad de Huechuraba', commune: 'Huechuraba', region: 'Metropolitana', paymentUrl: 'https://www.huechuraba.cl/permisos-de-circulacion', appointmentUrl: '', order: 45, active: true },
  { name: 'Municipalidad de San Antonio', commune: 'San Antonio', region: 'Valparaíso', paymentUrl: 'https://www.sanantonio.cl/permisos-de-circulacion', appointmentUrl: '', order: 46, active: true },
  { name: 'Municipalidad de Buin', commune: 'Buin', region: 'Metropolitana', paymentUrl: 'https://www.buin.cl/permisos-de-circulacion', appointmentUrl: '', order: 47, active: true },
  { name: 'Municipalidad de Estación Central', commune: 'Estación Central', region: 'Metropolitana', paymentUrl: 'https://www.municipalidadestacioncentral.cl/permisos-de-circulacion', appointmentUrl: '', order: 48, active: true },
  { name: 'Municipalidad de Padre Las Casas', commune: 'Padre Las Casas', region: 'La Araucanía', paymentUrl: 'https://www.padrelascasas.cl/permisos-de-circulacion', appointmentUrl: '', order: 49, active: true },
  { name: 'Municipalidad de Lota', commune: 'Lota', region: 'Biobío', paymentUrl: 'https://www.lota.cl/permisos-de-circulacion', appointmentUrl: '', order: 50, active: true },

  // ── Remaining communes (unverified — falls back to agendarhoras.cl) ───
  { name: 'Municipalidad de Alto Hospicio', commune: 'Alto Hospicio', region: 'Tarapacá', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Camarones', commune: 'Camarones', region: 'Arica y Parinacota', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Putre', commune: 'Putre', region: 'Arica y Parinacota', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de General Lagos', commune: 'General Lagos', region: 'Arica y Parinacota', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pozo Almonte', commune: 'Pozo Almonte', region: 'Tarapacá', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Camiña', commune: 'Camiña', region: 'Tarapacá', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Colchane', commune: 'Colchane', region: 'Tarapacá', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Huara', commune: 'Huara', region: 'Tarapacá', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pica', commune: 'Pica', region: 'Tarapacá', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Tocopilla', commune: 'Tocopilla', region: 'Antofagasta', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de María Elena', commune: 'María Elena', region: 'Antofagasta', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Ollagüe', commune: 'Ollagüe', region: 'Antofagasta', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Pedro de Atacama', commune: 'San Pedro de Atacama', region: 'Antofagasta', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Caldera', commune: 'Caldera', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Tierra Amarilla', commune: 'Tierra Amarilla', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chañaral', commune: 'Chañaral', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Diego de Almagro', commune: 'Diego de Almagro', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Vallenar', commune: 'Vallenar', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Huasco', commune: 'Huasco', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Freirina', commune: 'Freirina', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Alto del Carmen', commune: 'Alto del Carmen', region: 'Atacama', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Andacollo', commune: 'Andacollo', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Higuera', commune: 'La Higuera', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Paihuano', commune: 'Paihuano', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Vicuña', commune: 'Vicuña', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Monte Patria', commune: 'Monte Patria', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Punitaqui', commune: 'Punitaqui', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Combarbalá', commune: 'Combarbalá', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Canela', commune: 'Canela', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Los Vilos', commune: 'Los Vilos', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Salamanca', commune: 'Salamanca', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Illapel', commune: 'Illapel', region: 'Coquimbo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Petorca', commune: 'Petorca', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Ligua', commune: 'La Ligua', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cabildo', commune: 'Cabildo', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Zapallar', commune: 'Zapallar', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Papudo', commune: 'Papudo', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quillota', commune: 'Quillota', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Cruz', commune: 'La Cruz', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Calera', commune: 'La Calera', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Nogales', commune: 'Nogales', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Hijuelas', commune: 'Hijuelas', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cartagena', commune: 'Cartagena', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de El Tabo', commune: 'El Tabo', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de El Quisco', commune: 'El Quisco', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Algarrobo', commune: 'Algarrobo', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Santo Domingo', commune: 'Santo Domingo', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Felipe', commune: 'San Felipe', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Putaendo', commune: 'Putaendo', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Santa María', commune: 'Santa María', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Catemu', commune: 'Catemu', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Llay-Llay', commune: 'Llay-Llay', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Panquehue', commune: 'Panquehue', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Los Andes', commune: 'Los Andes', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Calle Larga', commune: 'Calle Larga', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Rinconada', commune: 'Rinconada', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Esteban', commune: 'San Esteban', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Limache', commune: 'Limache', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Olmué', commune: 'Olmué', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Casablanca', commune: 'Casablanca', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Juan Fernández', commune: 'Juan Fernández', region: 'Valparaíso', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Puerto Varas', commune: 'Puerto Varas', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Miguel', commune: 'San Miguel', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Cisterna', commune: 'La Cisterna', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Ramón', commune: 'San Ramón', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pedro Aguirre Cerda', commune: 'Pedro Aguirre Cerda', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lo Espejo', commune: 'Lo Espejo', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Granja', commune: 'La Granja', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Joaquín', commune: 'San Joaquín', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lo Prado', commune: 'Lo Prado', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cerro Navia', commune: 'Cerro Navia', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Renca', commune: 'Renca', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quinta Normal', commune: 'Quinta Normal', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Independencia', commune: 'Independencia', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Conchalí', commune: 'Conchalí', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cerrillos', commune: 'Cerrillos', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Macul', commune: 'Macul', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Reina', commune: 'La Reina', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Vitacura', commune: 'Vitacura', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lo Barnechea', commune: 'Lo Barnechea', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lampa', commune: 'Lampa', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Til-Til', commune: 'Til-Til', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pirque', commune: 'Pirque', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San José de Maipo', commune: 'San José de Maipo', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Calera de Tango', commune: 'Calera de Tango', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Paine', commune: 'Paine', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Alhué', commune: 'Alhué', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Curacaví', commune: 'Curacaví', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de María Pinto', commune: 'María Pinto', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Pedro', commune: 'San Pedro', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Talagante', commune: 'Talagante', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de El Monte', commune: 'El Monte', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Isla de Maipo', commune: 'Isla de Maipo', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Padre Hurtado', commune: 'Padre Hurtado', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Peñaflor', commune: 'Peñaflor', region: 'Metropolitana', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Machalí', commune: 'Machalí', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Graneros', commune: 'Graneros', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Mostazal', commune: 'Mostazal', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Codegua', commune: 'Codegua', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Doñihue', commune: 'Doñihue', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Olivar', commune: 'Olivar', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Coinco', commune: 'Coinco', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Coltauco', commune: 'Coltauco', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quinta de Tilcoco', commune: 'Quinta de Tilcoco', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Las Cabras', commune: 'Las Cabras', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Vicente', commune: 'San Vicente', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Peumo', commune: 'Peumo', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pichidegua', commune: 'Pichidegua', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Fernando', commune: 'San Fernando', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chimbarongo', commune: 'Chimbarongo', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Nancagua', commune: 'Nancagua', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Placilla', commune: 'Placilla', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chépica', commune: 'Chépica', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Santa Cruz', commune: 'Santa Cruz', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lolol', commune: 'Lolol', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pumanque', commune: 'Pumanque', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Palmilla', commune: 'Palmilla', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Peralillo', commune: 'Peralillo', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Navidad', commune: 'Navidad', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Litueche', commune: 'Litueche', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pichilemu', commune: 'Pichilemu', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Marchigüe', commune: 'Marchigüe', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Estrella', commune: 'La Estrella', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Paredones', commune: 'Paredones', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Rengo', commune: 'Rengo', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Requínoa', commune: 'Requínoa', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Malloa', commune: 'Malloa', region: "Libertador General Bernardo O'Higgins", paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Constitución', commune: 'Constitución', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Curepto', commune: 'Curepto', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Empedrado', commune: 'Empedrado', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Maule', commune: 'Maule', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pelarco', commune: 'Pelarco', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pencahue', commune: 'Pencahue', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Río Claro', commune: 'Río Claro', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Clemente', commune: 'San Clemente', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Rafael', commune: 'San Rafael', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cauquenes', commune: 'Cauquenes', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chanco', commune: 'Chanco', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pelluhue', commune: 'Pelluhue', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Hualañé', commune: 'Hualañé', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Licantén', commune: 'Licantén', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Molina', commune: 'Molina', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Rauco', commune: 'Rauco', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Romeral', commune: 'Romeral', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Sagrada Familia', commune: 'Sagrada Familia', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Teno', commune: 'Teno', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Vichuquén', commune: 'Vichuquén', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Javier', commune: 'San Javier', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Villa Alegre', commune: 'Villa Alegre', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Colbún', commune: 'Colbún', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Yerbas Buenas', commune: 'Yerbas Buenas', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Longaví', commune: 'Longaví', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Parral', commune: 'Parral', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Retiro', commune: 'Retiro', region: 'Maule', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chillán Viejo', commune: 'Chillán Viejo', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Bulnes', commune: 'Bulnes', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cobquecura', commune: 'Cobquecura', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Coelemu', commune: 'Coelemu', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Coihueco', commune: 'Coihueco', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de El Carmen', commune: 'El Carmen', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Ninhue', commune: 'Ninhue', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Ñiquén', commune: 'Ñiquén', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pemuco', commune: 'Pemuco', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pinto', commune: 'Pinto', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Portezuelo', commune: 'Portezuelo', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quillón', commune: 'Quillón', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quirihue', commune: 'Quirihue', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Ránquil', commune: 'Ránquil', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Carlos', commune: 'San Carlos', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Fabián', commune: 'San Fabián', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Ignacio', commune: 'San Ignacio', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Nicolás', commune: 'San Nicolás', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Treguaco', commune: 'Treguaco', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Yungay', commune: 'Yungay', region: 'Ñuble', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Alto Biobío', commune: 'Alto Biobío', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Antuco', commune: 'Antuco', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cabrero', commune: 'Cabrero', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Laja', commune: 'Laja', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Mulchén', commune: 'Mulchén', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Nacimiento', commune: 'Nacimiento', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Negrete', commune: 'Negrete', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quilaco', commune: 'Quilaco', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quilleco', commune: 'Quilleco', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Rosendo', commune: 'San Rosendo', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Santa Bárbara', commune: 'Santa Bárbara', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Tucapel', commune: 'Tucapel', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Yumbel', commune: 'Yumbel', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Hualqui', commune: 'Hualqui', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chiguayante', commune: 'Chiguayante', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Penco', commune: 'Penco', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Tomé', commune: 'Tomé', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lebu', commune: 'Lebu', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Arauco', commune: 'Arauco', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cañete', commune: 'Cañete', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Contulmo', commune: 'Contulmo', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Curanilahue', commune: 'Curanilahue', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Los Álamos', commune: 'Los Álamos', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Tirúa', commune: 'Tirúa', region: 'Biobío', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Angol', commune: 'Angol', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Collipulli', commune: 'Collipulli', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Curacautín', commune: 'Curacautín', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Ercilla', commune: 'Ercilla', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lonquimay', commune: 'Lonquimay', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Los Sauces', commune: 'Los Sauces', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lumaco', commune: 'Lumaco', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Purén', commune: 'Purén', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Renaico', commune: 'Renaico', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Traiguén', commune: 'Traiguén', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Victoria', commune: 'Victoria', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Villarrica', commune: 'Villarrica', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pucón', commune: 'Pucón', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Curarrehue', commune: 'Curarrehue', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Freire', commune: 'Freire', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Gorbea', commune: 'Gorbea', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Loncoche', commune: 'Loncoche', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Pitrufquén', commune: 'Pitrufquén', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Toltén', commune: 'Toltén', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Carahue', commune: 'Carahue', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cholchol', commune: 'Cholchol', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Nueva Imperial', commune: 'Nueva Imperial', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Saavedra', commune: 'Saavedra', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Teodoro Schmidt', commune: 'Teodoro Schmidt', region: 'La Araucanía', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Corral', commune: 'Corral', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Futrono', commune: 'Futrono', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de La Unión', commune: 'La Unión', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lago Ranco', commune: 'Lago Ranco', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lanco', commune: 'Lanco', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Los Lagos', commune: 'Los Lagos', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Máfil', commune: 'Máfil', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Mariquina', commune: 'Mariquina', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Paillaco', commune: 'Paillaco', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Panguipulli', commune: 'Panguipulli', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Río Bueno', commune: 'Río Bueno', region: 'Los Ríos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Calbuco', commune: 'Calbuco', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cochamó', commune: 'Cochamó', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Fresia', commune: 'Fresia', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Frutillar', commune: 'Frutillar', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Los Muermos', commune: 'Los Muermos', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Llanquihue', commune: 'Llanquihue', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Maullín', commune: 'Maullín', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Ancud', commune: 'Ancud', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Castro', commune: 'Castro', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chonchi', commune: 'Chonchi', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Curaco de Vélez', commune: 'Curaco de Vélez', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Dalcahue', commune: 'Dalcahue', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Puqueldón', commune: 'Puqueldón', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Queilén', commune: 'Queilén', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quellón', commune: 'Quellón', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quemchi', commune: 'Quemchi', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Quinchao', commune: 'Quinchao', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Puerto Octay', commune: 'Puerto Octay', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Purranque', commune: 'Purranque', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Puyehue', commune: 'Puyehue', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Río Negro', commune: 'Río Negro', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Juan de la Costa', commune: 'San Juan de la Costa', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Pablo', commune: 'San Pablo', region: 'Los Lagos', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Coihaique', commune: 'Coihaique', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Lago Verde', commune: 'Lago Verde', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Aysén', commune: 'Aysén', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cisnes', commune: 'Cisnes', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Guaitecas', commune: 'Guaitecas', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Chile Chico', commune: 'Chile Chico', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Río Ibáñez', commune: 'Río Ibáñez', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cochrane', commune: 'Cochrane', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de O\'Higgins', commune: 'O\'Higgins', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Tortel', commune: 'Tortel', region: 'Aysén del General Carlos Ibáñez del Campo', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Laguna Blanca', commune: 'Laguna Blanca', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Río Verde', commune: 'Río Verde', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de San Gregorio', commune: 'San Gregorio', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Cabo de Hornos', commune: 'Cabo de Hornos', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Antártica', commune: 'Antártica', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Porvenir', commune: 'Porvenir', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Primavera', commune: 'Primavera', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Timaukel', commune: 'Timaukel', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Natales', commune: 'Natales', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
  { name: 'Municipalidad de Torres del Paine', commune: 'Torres del Paine', region: 'Magallanes y de la Antártica Chilena', paymentUrl: '', appointmentUrl: '', order: 100, active: true },
];

const now = new Date();

async function seed() {
  console.log(`🌱 Seeding ${MUNICIPALITIES.length} municipalities...`);

  for (const m of MUNICIPALITIES) {
    const id = crypto.randomUUID();

    await db.insert(municipalities).values({
      id,
      name: m.name,
      commune: m.commune,
      region: m.region,
      paymentUrl: m.paymentUrl,
      appointmentUrl: m.appointmentUrl,
      active: m.active,
      order: m.order,
      createdAt: now,
      updatedAt: now,
    });
  }

  console.log('✅ Seed complete!');
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
