import React, { createContext, useContext, useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'es';

const translations = {
  en: {
    // Tabs
    tabHome: 'Home',
    tabMotos: 'Motos',
    tabProfile: 'Profile',
    tabManualPublication: 'Publish',
    // Manual Publication
    manualPublicationTitle: 'Manual Publication',
    manualPublicationSubtitle: 'Report a theft without GPS',
    selectMotorcycle: 'Select Motorcycle',
    noMotorcyclesAvailable: 'No motorcycles registered',
    locationOptional: 'Location',
    locationPlaceholder: 'Describe where it was last seen',
    useCurrentLocation: 'Use current location',
    additionalNotes: 'Additional notes',
    notesPlaceholder: 'Any relevant details...',
    publishAlert: 'Publish Alert',
    publishConfirm: 'Are you sure you want to publish this theft alert?',
    publicationSuccess: 'Alert published successfully',
    publicationError: 'Failed to publish alert',
    // Nearby Services
    nearbyServices: 'Nearby Services',
    nearbyServicesEmpty: 'Workshops, medical centers and more near you',
    loadingPlaces: 'Searching nearby...',
    // Home
    homeTitle: 'Welcome to Moto Tracker',
    homeSubtitle: 'Track your motorcycle maintenance and documents',
    registerFirstMoto: 'Register your first motorcycle to see its status here',
    theftAlerts: 'Theft Alerts',
    noActiveAlerts: 'All clear for now',
    theftAlertsEmpty: 'Alerts only appear when your motorcycle leaves the safe zone, or when someone nearby reports a theft. No spam.',
    saveOnRoute: 'Save on your route',
    nearbyOffers: 'Nearby offers',
    saveOnRouteEmpty: 'Gas, wash and more deals near you',
    gpsTracking: 'GPS Tracking',
    gpsActive: 'Tracking active',
    gpsInactive: 'Activate to track location',
    gpsQuestion: 'Do you have open protocol trackers to register your motorcycle?',
    gpsQuestionHint: 'If so, enter the GPS ID or name to link it to tracking.',
    gpsIdPlaceholder: 'GPS ID or name (optional)',
    viewOnMap: 'View on map',
    noGpsRegistered: 'No GPS tracker registered',
    noGpsRegisteredHint: 'Add a GPS ID to your motorcycle to enable tracking',
    sessionExpired: 'Session expired. Please log in again.',
    myPublications: 'My Publications',
    outOfZone: 'OUT OF ZONE',
    inSafeZone: 'IN SAFE ZONE',
    noData: 'NO DATA',
    enableGpsToTrack: 'Enable GPS to track location',
    enableGps: 'Enable GPS',
    waitingForSignal: 'Waiting for signal',
    searchingLocation: 'Searching for location...',
    noMotoAssigned: 'No motorcycle assigned',
    lastLocation: 'LAST LOCATION',
    parkedAtLocation: 'Parked at location - 6 minutes ago',
    locationPermissionNeeded: 'Location permission is needed to track your motorcycle',
    gettingLocation: 'Getting location...',
    mapView: 'Map view',
    currentCoords: 'Current coordinates',
    speed: 'Speed',
    heading: 'Heading',
    lastUpdate: 'Last update',
    goBack: 'Go back',
    // Active Moto
    activeMoto: 'Active motorcycle',
    activateMoto: 'Activate this motorcycle',
    deactivateMoto: 'Deactivate use',
    reportTheft: 'Report theft',
    parkedAt: 'Parked at',
    activeSince: 'Active since',
    selectMoto: 'Select your motorcycle',
    longPressToActivate: 'Long press to activate motorcycle',
    longPressForActions: 'Long press for actions',
    // Notifications
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications',
    noNotificationsText: 'You will see alerts and responses here',
    // Motorcycles
    myMotorcycles: 'My Motorcycles',
    noMotorcycles: 'No motorcycles yet',
    noMotorcyclesSub: 'Tap + to add your first motorcycle',
    addMotorcycle: 'Add Motorcycle',
    // Forms
    brand: 'Brand',
    model: 'Model',
    year: 'Year',
    licensePlate: 'License Plate',
    currentKilometers: 'Current Kilometers',
    save: 'Save',
    cancel: 'Cancel',
    no: 'No',
    delete: 'Delete',
    edit: 'Edit',
    // Documents
    documents: 'Documents',
    // Profile
    account: 'Account',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    googleAccount: 'Google Account',
    connected: 'Connected',
    appSettings: 'App Settings',
    notifications: 'Notifications',
    protocolTraker: 'Open Protocol Tracker',
    protocolTrakerInfo: 'To register your motorcycle you need a GPS tracker with open protocol (e.g. GT06, JT808). We recommend 4G models — 2G/3G-only devices are losing coverage in Chile.',
    viewExample: 'View example',
    theme: 'Theme',
    language: 'Language',
    biometric: 'Fingerprint Login',
    biometricPromptTitle: 'Enable Fingerprint Login?',
    biometricPromptMessage: 'Do you want to enable fingerprint authentication for faster login?',
    noBiometricsRegistered: 'No fingerprints registered on this device. Please add one in your phone settings first.',
    noBiometricHardware: 'This device does not support fingerprint authentication.',
    biometricSetupTitle: 'Fingerprint Setup Required',
    biometricSetupMessage: 'You need to register a fingerprint on your device first. Open settings to add one?',
    openSettings: 'Open Settings',
    support: 'Support',
    appTutorial: 'Application Tutorial',
    helpSupport: 'Help & Support',
    about: 'About',
    signOut: 'Sign Out',
    signOutConfirm: 'Are you sure you want to sign out?',
    // Password
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    passwordChanged: 'Password changed successfully',
    // Theme
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    // Language
    english: 'English',
    spanish: 'Español',
    // Maintenance
    maintenance: 'Maintenance',
    serviceDate: 'Service Date',
    description: 'Description',
    kilometers: 'Kilometers',
    cost: 'Cost',
    notes: 'Notes',
    // Kilometers
    kilometerLog: 'Kilometer Log',
    recordedAt: 'Recorded At',
    readingKm: 'Reading (km)',
    // Motorcycle Detail
    motorcycleDetail: 'Motorcycle Detail',
    maintenanceRecords: 'Maintenance Records',
    kilometerHistory: 'Kilometer History',
    sections: 'Sections',
    editMotorcycle: 'Edit Motorcycle',
    motorcycleNotFound: 'Motorcycle not found',
    failedToLoad: 'Failed to load motorcycle',
    motorcycleUpdated: 'Motorcycle updated',
    failedToUpdate: 'Failed to update',
    deleteMotorcycle: 'Delete Motorcycle',
    deleteConfirm: 'This action cannot be undone.',
    failedToDelete: 'Failed to delete',
    // Maintenance Screen
    addRecord: 'Add Record',
    noRecords: 'No maintenance records yet',
    noRecordsSub: 'Tap + to log maintenance',
    newRecord: 'New Record',
    editRecord: 'Edit Record',
    recordSaved: 'Record saved',
    recordUpdated: 'Record updated',
    failedToCreate: 'Failed to create',
    deleteRecord: 'Delete Record',
    // Type labels
    oilChange: 'Oil Change',
    tireChange: 'Tire Change',
    brakeCheck: 'Brake Check',
    sparkPlugs: 'Spark Plugs',
    technicalReview: 'Technical Review',
    circulationPermit: 'Circulation Permit',
    insurance: 'Insurance',
    registration: 'Registration',
    padron: 'Padron',
    driversLicense: "Driver's License",
    fines: 'Fines',
    other: 'Other',
    // Documents Screen
    addDocument: 'Add Document',
    noDocuments: 'No documents yet',
    noDocumentsSub: 'Tap + to add a document',
    documentsDisclaimer: 'These documents must be kept up to date for inspections or renewals. Keep in mind that as digital documents, they are not valid for police checks.',
    newDocument: 'New Document',
    editDocument: 'Edit Document',
    documentSaved: 'Document saved',
    documentUpdated: 'Document updated',
    deleteDocument: 'Delete Document',
    addDocumentPhoto: 'Add Document Photo',
    addMotoPhoto: 'Add Vehicle Photo',
    chooseOption: 'Choose an option',
    takePhoto: 'Take Photo',
    chooseFromGallery: 'Choose from Gallery',
    permissionNeeded: 'Permission needed',
    permissionMessage: 'Please grant camera permission.',
    title: 'Title',
    issueDate: 'Issue date',
    expiryDate: 'Expiry date',
    tapToAddPhoto: 'Tap to add document photo',
    frontPhoto: 'Front photo',
    backPhoto: 'Back photo',
    tapToAddMotoPhoto: 'Tap to add vehicle photo',
    saveAll: 'Save All',
    saveAsPdf: 'Save as PDF',
    download: 'Download',
    share: 'Share',
    done: 'Done',
    noDocumentAttached: 'No document attached',
    tapToView: 'Tap to view',
    issued: 'Issued',
    expires: 'Expires',
    valid: 'Valid',
    expiring: 'Expiring',
    expired: 'Expired',
    noPhotos: 'No photos',
    noPhotosSub: 'No documents with photos to save.',
    failedToSave: 'Failed to save',
    failedToShare: 'Failed to share',
    expiryBeforeIssue: 'Expiry date must be after issue date',
    // Kilometers Screen
    addEntry: 'Add Entry',
    noEntries: 'No kilometer entries yet',
    noEntriesSub: 'Tap + to record mileage',
    newReading: 'New Reading',
    editReading: 'Edit Reading',
    readingSaved: 'Reading saved',
    readingUpdated: 'Reading updated',
    deleteEntry: 'Delete Entry',
    selectDate: 'Select date',
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    required: 'Required',
    optional: 'Optional',
    // About
    aboutTitle: 'About Moto Tracker',
    aboutVersion: 'Version 1.0.0',
    aboutDescription: 'Track your motorcycle maintenance and documents in one place.',
    // Help
    helpTitle: 'Help & Support',
    helpMessage: 'For support, contact us at jdevlabs.cl@gmail.com',
    // Profile Edit
    changePhoto: 'Change Photo',
    profileUpdated: 'Profile updated successfully',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    camera: 'Camera',
    gallery: 'Gallery',
    cameraPermission: 'Camera permission is required',
    // Auth
    signInTitle: 'Sign in to your account',
    signInButton: 'Sign In',
    signInLoading: 'Signing in...',
    signUpTitle: 'Create Account',
    signUpSubtitle: 'Sign up to start tracking',
    signUpButton: 'Sign Up',
    signUpLoading: 'Creating account...',
    or: 'or',
    continueWithGoogle: 'Continue with Google',
    googleComingSoon: 'Coming soon — requires development build',
    noAccount: "Don't have an account? Sign Up",
    hasAccount: 'Already have an account? Sign In',
    fillAllFields: 'Please fill in all fields',
    loginFailed: 'Login failed',
    registrationFailed: 'Registration failed',
    invalidPhone: 'Enter a valid phone: +569XXXXXXXX',
    password: 'Password',
  },
  es: {
    // Tabs
    tabHome: 'Inicio',
    tabMotos: 'Motos',
    tabProfile: 'Perfil',
    tabManualPublication: 'Publicar',
    // Manual Publication
    manualPublicationTitle: 'Publicación Manual',
    manualPublicationSubtitle: 'Reportar un robo sin GPS',
    selectMotorcycle: 'Seleccionar Moto',
    noMotorcyclesAvailable: 'No hay motos registradas',
    locationOptional: 'Ubicación',
    locationPlaceholder: 'Describe dónde fue vista por última vez',
    useCurrentLocation: 'Usar ubicación actual',
    additionalNotes: 'Notas adicionales',
    notesPlaceholder: 'Detalles relevantes...',
    publishAlert: 'Publicar Alerta',
    publishConfirm: '¿Estás seguro de que quieres publicar esta alerta de robo?',
    publicationSuccess: 'Alerta publicada exitosamente',
    publicationError: 'Error al publicar alerta',
    // Nearby Services
    nearbyServices: 'Servicios cercanos',
    nearbyServicesEmpty: 'Talleres, centros médicos y más cerca de ti',
    loadingPlaces: 'Buscando cercanos...',
    // Home
    homeTitle: 'Bienvenido a Moto Tracker',
    homeSubtitle: 'Seguimiento del mantenimiento y documentos de tu moto',
    registerFirstMoto: 'Registra tu primera moto para ver su estado aquí',
    theftAlerts: 'Alertas de robo',
    noActiveAlerts: 'Todo tranquilo por ahora',
    theftAlertsEmpty: 'Solo recibirás notificaciones cuando tu moto salga de su zona segura, o cuando alguien cerca reporta un robo. Nada de spam.',
    saveOnRoute: 'Ahorra en tu ruta',
    nearbyOffers: 'Ofertas cercanas',
    saveOnRouteEmpty: 'Ofertas de bencina, lavado y más cerca de ti',
    gpsTracking: 'Rastreo GPS',
    gpsActive: 'Rastreo activo',
    gpsInactive: 'Activa para rastrear ubicación',
    gpsQuestion: '¿Tienes Rastreadores con protocolo abierto para registrar tu moto?',
    gpsQuestionHint: 'Si es así, ingresa el ID o nombre del GPS para vincularlo al rastreo.',
    gpsIdPlaceholder: 'GPS ID o nombre (opcional)',
    viewOnMap: 'Ver en mapa',
    noGpsRegistered: 'Sin rastreador GPS registrado',
    noGpsRegisteredHint: 'Agrega un ID de GPS a tu moto para habilitar el rastreo',
    sessionExpired: 'Sesión expirada. Por favor inicia sesión nuevamente.',
    myPublications: 'Mis publicaciones',
    outOfZone: 'FUERA DE ZONA',
    inSafeZone: 'EN ZONA SEGURA',
    noData: 'SIN DATOS',
    enableGpsToTrack: 'Activa el GPS para rastrear ubicación',
    enableGps: 'Activar GPS',
    waitingForSignal: 'Esperando señal',
    searchingLocation: 'Buscando ubicación...',
    noMotoAssigned: 'Sin moto asignada',
    lastLocation: 'ÚLTIMA UBICACIÓN',
    parkedAtLocation: 'Estacionada en ubicación - hace 6 minutos',
    locationPermissionNeeded: 'Se necesita permiso de ubicación para rastrear tu moto',
    gettingLocation: 'Obteniendo ubicación...',
    mapView: 'Vista de mapa',
    currentCoords: 'Coordenadas actuales',
    speed: 'Velocidad',
    heading: 'Rumbo',
    lastUpdate: 'Última actualización',
    goBack: 'Volver',
    // Active Moto
    activeMoto: 'Moto en uso',
    activateMoto: 'Activar esta moto',
    deactivateMoto: 'Desactivar uso',
    reportTheft: 'Reportar robo',
    parkedAt: 'Estacionada en',
    activeSince: 'Activa hace',
    selectMoto: 'Selecciona tu moto',
    longPressToActivate: 'Mantén presionado para activar moto',
    longPressForActions: 'Mantén presionado para acciones',
    // Notifications
    notifications: 'Notificaciones',
    markAllRead: 'Marcar todo leído',
    noNotifications: 'Sin notificaciones',
    noNotificationsText: 'Verás alertas y respuestas aquí',
    // Motorcycles
    myMotorcycles: 'Mis Motos',
    noMotorcycles: 'Aún no hay motos',
    noMotorcyclesSub: 'Toca + para agregar tu primera moto',
    addMotorcycle: 'Agregar Moto',
    // Forms
    brand: 'Marca',
    model: 'Modelo',
    year: 'Año',
    licensePlate: 'Patente',
    currentKilometers: 'Kilometraje Actual',
    save: 'Guardar',
    cancel: 'Cancelar',
    no: 'No',
    delete: 'Eliminar',
    edit: 'Editar',
    // Documents
    documents: 'Documentos',
    // Profile
    account: 'Cuenta',
    editProfile: 'Editar Perfil',
    changePassword: 'Cambiar Contraseña',
    googleAccount: 'Cuenta de Google',
    connected: 'Conectado',
    appSettings: 'Configuración',
    notifications: 'Notificaciones',
    protocolTraker: 'Rastreador de Protocolo Abierto',
    protocolTrakerInfo: 'Para registrar tu moto necesitas un rastreador GPS de protocolo abierto (ej. GT06, JT808). Recomendamos modelos 4G — los de solo 2G/3G están quedando fuera de cobertura en Chile.',
    viewExample: 'Ver ejemplo',
    theme: 'Tema',
    language: 'Idioma',
    biometric: 'Inicio con huella',
    biometricPromptTitle: '¿Activar inicio con huella?',
    biometricPromptMessage: '¿Deseas activar la autenticación por huella para un acceso más rápido?',
    noBiometricsRegistered: 'No hay huellas registradas en este dispositivo. Por favor, agrega una en la configuración de tu teléfono primero.',
    noBiometricHardware: 'Este dispositivo no soporta autenticación por huella.',
    biometricSetupTitle: 'Configuración de Huella Requerida',
    biometricSetupMessage: 'Necesitas registrar una huella en tu dispositivo primero. ¿Abrir configuración para agregar una?',
    openSettings: 'Abrir Configuración',
    support: 'Soporte',
    appTutorial: 'Tutorial de la Aplicación',
    helpSupport: 'Ayuda y Soporte',
    about: 'Acerca de',
    signOut: 'Cerrar Sesión',
    signOutConfirm: '¿Estás seguro de que quieres cerrar sesión?',
    // Password
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Nueva Contraseña',
    passwordChanged: 'Contraseña cambiada exitosamente',
    // Theme
    lightMode: 'Modo Claro',
    darkMode: 'Modo Oscuro',
    // Language
    english: 'English',
    spanish: 'Español',
    // Maintenance
    maintenance: 'Mantenimiento',
    serviceDate: 'Fecha de Servicio',
    description: 'Descripción',
    kilometers: 'Kilometraje',
    cost: 'Costo',
    notes: 'Notas',
    // Kilometers
    kilometerLog: 'Registro de Kilometraje',
    recordedAt: 'Fecha de Registro',
    readingKm: 'Lectura (km)',
    // Motorcycle Detail
    motorcycleDetail: 'Detalle de Moto',
    maintenanceRecords: 'Registros de Mantenimiento',
    kilometerHistory: 'Historial de Kilometraje',
    sections: 'Secciones',
    editMotorcycle: 'Editar Moto',
    motorcycleNotFound: 'Moto no encontrada',
    failedToLoad: 'Error al cargar moto',
    motorcycleUpdated: 'Moto actualizada',
    failedToUpdate: 'Error al actualizar',
    deleteMotorcycle: 'Eliminar Moto',
    deleteConfirm: 'Esta acción no se puede deshacer.',
    failedToDelete: 'Error al eliminar',
    // Maintenance Screen
    addRecord: 'Agregar Registro',
    noRecords: 'Aún no hay registros de mantenimiento',
    noRecordsSub: 'Toca + para registrar mantenimiento',
    newRecord: 'Nuevo Registro',
    editRecord: 'Editar Registro',
    recordSaved: 'Registro guardado',
    recordUpdated: 'Registro actualizado',
    failedToCreate: 'Error al crear',
    deleteRecord: 'Eliminar Registro',
    // Type labels
    oilChange: 'Cambio de Aceite',
    tireChange: 'Cambio de Cubiertas',
    brakeCheck: 'Revisión de Frenos',
    sparkPlugs: 'Bujías',
    technicalReview: 'Revisión Técnica',
    circulationPermit: 'Permiso de Circulación',
    insurance: 'Seguro Obligatorio',
    registration: 'Registro',
    padron: 'Padrón',
    driversLicense: 'Licencia de Conducir',
    fines: 'Multas',
    other: 'Otro',
    // Documents Screen
    addDocument: 'Agregar Documento',
    noDocuments: 'Aún no hay documentos',
    noDocumentsSub: 'Toca + para agregar un documento',
    documentsDisclaimer: 'Estos documentos deben mantenerse al día para fiscalizaciones o renovaciones. Considera que al ser documentos de carácter digital, no sirven para controles policiales.',
    newDocument: 'Nuevo Documento',
    editDocument: 'Editar Documento',
    documentSaved: 'Documento guardado',
    documentUpdated: 'Documento actualizado',
    deleteDocument: 'Eliminar Documento',
    addDocumentPhoto: 'Agregar Foto de Documento',
    addMotoPhoto: 'Agregar Foto del Vehículo',
    chooseOption: 'Elige una opción',
    takePhoto: 'Tomar Foto',
    chooseFromGallery: 'Elegir de Galería',
    permissionNeeded: 'Permiso requerido',
    permissionMessage: 'Por favor concede permiso de cámara.',
    issueDate: 'Fecha de emisión',
    expiryDate: 'Fecha de vencimiento',
    tapToAddPhoto: 'Toca para agregar foto del documento',
    frontPhoto: 'Foto frontal',
    backPhoto: 'Foto reverso',
    tapToAddMotoPhoto: 'Toca para agregar foto del vehículo',
    saveAll: 'Guardar Todo',
    saveAsPdf: 'Guardar como PDF',
    download: 'Descargar',
    share: 'Compartir',
    done: 'Listo',
    noDocumentAttached: 'Sin documento adjunto',
    tapToView: 'Toca para ver',
    issued: 'Emitido',
    expires: 'Vence',
    valid: 'Válido',
    expiring: 'Por vencer',
    expired: 'Vencido',
    noPhotos: 'Sin fotos',
    noPhotosSub: 'No hay documentos con fotos para guardar.',
    failedToSave: 'Error al guardar',
    failedToShare: 'Error al compartir',
    expiryBeforeIssue: 'La fecha de vencimiento debe ser posterior a la fecha de emisión',
    // Kilometers Screen
    addEntry: 'Agregar Entrada',
    noEntries: 'Aún no hay entradas de kilometraje',
    noEntriesSub: 'Toca + para registrar lectura',
    newReading: 'Nueva Lectura',
    editReading: 'Editar Lectura',
    readingSaved: 'Lectura guardada',
    readingUpdated: 'Lectura actualizada',
    deleteEntry: 'Eliminar Entrada',
    selectDate: 'Seleccionar fecha',
    // Common
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    required: 'Requerido',
    optional: 'Opcional',
    // About
    aboutTitle: 'Acerca de Moto Tracker',
    aboutVersion: 'Versión 1.0.0',
    aboutDescription: 'Seguimiento del mantenimiento y documentos de tu moto en un solo lugar.',
    // Help
    helpTitle: 'Ayuda y Soporte',
    helpMessage: 'Para soporte, contáctanos en jdevlabs.cl@gmail.com',
    // Profile Edit
    changePhoto: 'Cambiar Foto',
    profileUpdated: 'Perfil actualizado exitosamente',
    name: 'Nombre',
    email: 'Email',
    phone: 'Teléfono',
    camera: 'Cámara',
    gallery: 'Galería',
    cameraPermission: 'Se requiere permiso de cámara',
    // Auth
    signInTitle: 'Inicia sesión en tu cuenta',
    signInButton: 'Iniciar Sesión',
    signInLoading: 'Iniciando sesión...',
    signUpTitle: 'Crear Cuenta',
    signUpSubtitle: 'Regístrate para comenzar a rastrear',
    signUpButton: 'Registrarse',
    signUpLoading: 'Creando cuenta...',
    or: 'o',
    continueWithGoogle: 'Continuar con Google',
    googleComingSoon: 'Próximamente — requiere build de desarrollo',
    noAccount: '¿No tienes cuenta? Regístrate',
    hasAccount: '¿Ya tienes cuenta? Inicia Sesión',
    fillAllFields: 'Por favor completa todos los campos',
    loginFailed: 'Error al iniciar sesión',
    registrationFailed: 'Error al registrarse',
    invalidPhone: 'Ingresa un teléfono válido: +569XXXXXXXX',
    password: 'Contraseña',
  },
};

type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  t: (key: TranslationKey) => string;
  setLanguage: (lang: Language) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    (async () => {
      const saved = await AsyncStorage.getItem('language');
      if (saved === 'en' || saved === 'es') {
        setLanguageState(saved);
      }
      setLoaded(true);
    })();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem('language', lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  if (!loaded) return null;

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}